//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeödeviUcakrezervasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_Ucak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public U_Ucak()
        {
            this.U_SEFERLER = new HashSet<U_SEFERLER>();
        }
    
        public int Ucak_Id { get; set; }
        public string Ucak_Ad { get; set; }
        public Nullable<int> Koltuk_Sayısı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<U_SEFERLER> U_SEFERLER { get; set; }
    }
}
