//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeödeviUcakrezervasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_BİLET
    {
        public int Bilet_Id { get; set; }
        public Nullable<int> Yolcu_Id { get; set; }
        public Nullable<int> Sefer_Id { get; set; }
        public string Koltuk_No { get; set; }
    
        public virtual U_SEFERLER U_SEFERLER { get; set; }
        public virtual U_YOLCU U_YOLCU { get; set; }
    }
}
