//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeödeviUcakrezervasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_SEFERLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public U_SEFERLER()
        {
            this.U_BİLET = new HashSet<U_BİLET>();
        }
    
        public int Sefer_Id { get; set; }
        public string Kalkış_Yer { get; set; }
        public string Varış_Yer { get; set; }
        public string Kalkış_Tarih { get; set; }
        public string Varıs_Tarih { get; set; }
        public Nullable<int> Ucak_Id { get; set; }
        public string Ücret { get; set; }
        public string Sefer_Ad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<U_BİLET> U_BİLET { get; set; }
        public virtual U_Ucak U_Ucak { get; set; }
    }
}
