//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeödeviUcakrezervasyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ucak_rezervasyonSonEntities : DbContext
    {
        public Ucak_rezervasyonSonEntities()
            : base("name=Ucak_rezervasyonSonEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<U_BİLET> U_BİLET { get; set; }
        public virtual DbSet<U_SEFERLER> U_SEFERLER { get; set; }
        public virtual DbSet<U_Ucak> U_Ucak { get; set; }
        public virtual DbSet<U_YOLCU> U_YOLCU { get; set; }
    }
}
